name: Manual Zip Deploy to Azure Web App

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Create zip package
        run: |
          zip -r app.zip . -x "*.git*" "node_modules/*" ".github/*"

      - name: Deploy to Azure Web App (ZipDeploy)
        run: |
          curl -X POST "https://${{ secrets.AZURE_WEBAPP_PUBLISH_URL }}/api/zipdeploy" \
          -u "${{ secrets.AZURE_WEBAPP_USERNAME }}:${{ secrets.AZURE_WEBAPP_PASSWORD }}" \
          --data-binary "@app.zip"
